# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    - name: Deploy to Firebase Hosting
  # You may pin to the exact commit or the version.
  # uses: FirebaseExtended/action-hosting-deploy@276388dd6c2cde23455b30293105cc866c22282d
  uses: FirebaseExtended/action-hosting-deploy@v0.6-alpha
  with:
    # The GITHUB_TOKEN secret
    repoToken: # optional
    # Firebase service account JSON
    firebaseServiceAccount: 
    # How long should a preview live? See the preview channels docs for options
    expires: # optional, default is 7d
    # The project to deploy to. If you leave this blank, make sure you check in a .firebaserc file
    projectId: # optional
    # The ID of the channel to deploy to. If you leave this blank, a preview channel and its ID will be auto-generated per branch or PR.
    channelId: # optional
    # The target name of the Hosting site to deploy to. If you leave this blank, the default target or all targets defined in the .firebaserc will be deployed to. Refer to the Hosting docs about [multiple sites](https://firebase.google.com/docs/hosting/multisites) for more information about deploy targets.
    target: # optional
    # The location of your firebase.json file, relative to the root of your directory
    entryPoint: # optional, default is .
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
